### ISSUE TITLE
train.hdf5 without error, test.hdf5 comes with error

### ISSUE THREAD

**Issue by ttkrpink** [physhik/ecg-mit-bih#12]
Python 3.6.8,
numpy 1.16.0
Other files are the same.

data.py with train set works fine.
It seems the test set has the following error.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [30:42<00:00, 48.46s/it]
 12%|████████████████▉                                                                                                                      | 1/8 [00:42<04:55, 42.26s/it]Traceback (most recent call last):█████████████████████████████████████████████████████████████████████████████████████████████████████| 3626/3626 [00:42<00:00, 47.51it/s]
  File "src/data.py", line 136, in <module>
    main(config)
  File "src/data.py", line 132, in main
    return preprocess(config.split)
  File "src/data.py", line 114, in preprocess
    dataSaver(testset, 'dataset/test.hdf5', 'dataset/testlabel.hdf5')
  File "src/data.py", line 92, in dataSaver
    dataprocess()
  File "src/data.py", line 60, in dataprocess
    record = rdrecord('dataset/'+ num, smooth_frames= True)
  File "F:\PyThon\virtual\36\lib\site-packages\wfdb\io\record.py", line 1232, in rdrecord
    ignore_skew)
  File "F:\PyThon\virtual\36\lib\site-packages\wfdb\io\_signal.py", line 876, in _rd_segment
    smooth_frames)[:, r_w_channel[fn]]
  File "F:\PyThon\virtual\36\lib\site-packages\wfdb\io\_signal.py", line 974, in _rd_dat_signals
    sig_data = _blocks_to_samples(sig_data, total_process_samples, fmt)
  File "F:\PyThon\virtual\36\lib\site-packages\wfdb\io\_signal.py", line 1269, in _blocks_to_samples
    sig[0::2] = sig_data[0::3] + 256 * np.bitwise_and(sig_data[1::3], 0x0f)
ValueError: could not broadcast input array from shape (283885) into shape (650000)
Exception ignored in: <bound method tqdm.__del__ of  12%|████████████████▉                                                                                                                      | 1/8 [00:42<04:55, 42.26s/it]>
Traceback (most recent call last):
  File "F:\PyThon\virtual\36\lib\site-packages\tqdm\_tqdm.py", line 931, in __del__
    self.close()
  File "F:\PyThon\virtual\36\lib\site-packages\tqdm\_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "F:\PyThon\virtual\36\lib\site-packages\tqdm\_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "F:\PyThon\virtual\36\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "F:\PyThon\3.6.8\lib\threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。

**Comment by Shasmita** [comment]
Were you able to solve the above issue and run the application successfully?

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。

**Comment by sg4395** [comment]
Hi were you able to work this out?

**Comment by physhik** [comment]
I have never experienced such an error before. I will check out

**Comment by sg4395** [comment]
Thank you, please let me know!

Best,
ASEAN

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sg4395** [comment]
Hi Namshik,

Were you able to take a look at the code and see if it runs? I think maybe the hdf5 file isn't being created for some reason. App.py encounters similar issue. By the way do you know if app.py requires the data to be 300+hz like the data you trained the model with? Or does it take any sampling rate data ?

Best,
Sean

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sg4395** [comment]
> I have never experienced such an error before. I will check out

Hi Namshik,
were you able to get it working?
