### ISSUE TITLE
Value Error on running python3 train.py 

### ISSUE THREAD

**Issue by 0xamogh** [physhik/ecg-mit-bih#2]
Please help me out with your tensorflow versioning
The following is the stack trace of the error
`Traceback (most recent call last):
  File "train.py", line 60, in <module>
    main(config)
  File "train.py", line 56, in main
    train(config, X, y, Xval, yval)
  File "train.py", line 46, in train
    initial_epoch=initial_epoch)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1213, in fit
    self._make_train_function()
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/keras/engine/training.py", line 316, in _make_train_function
    loss=self.total_loss)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/keras/optimizers.py", line 543, in get_updates
    p_t = p - lr_t * m_t / (K.sqrt(v_t) + self.epsilon)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 888, in binary_op_wrapper
    y, dtype_hint=x.dtype.base_dtype, name="y")
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1158, in convert_to_tensor_v2
    as_ref=False)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1237, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/amoghjrules/.local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 455, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
`

**Comment by physhik** [comment]
Downgrade the numpy, and it'll work. Also recommend using Python virtual environment. 

$pip install numpy==1.15.4
